language: scala
scala:
- 2.10.2
script:
- mvn clean test package
jdk:
- openjdk6
env:
  secure: XZMYRnZr5zIRkTPYo5TMCWmJ9GL1TvVtwIwgZG1uUgwxkTnAHlS7B+UaIyOvYAwBt0Esy29FA+d2tbv6ThLpLORY6VzqKjFaZolIfrboQ5oUJ7V5KVu/3DjjksQy2nIYrdrFo4mJITFOMw8ENgHgZeOL2WJnRE3ntAJsRWxNMrM=
